// esbuild driver: two bundles.
//
//   1. src/extension.ts → extension.mjs — the Node entry the CLI loads. The
//      Copilot SDK is marked external (CLI auto-resolves it; never bundle).
//      Octokit + @actions/workflow-parser (which pulls in yaml) are bundled in
//      so the extension is a single self-contained ESM file with no runtime
//      node_modules dependency.
//   2. web/main.tsx → web/main.js (+ web/main.css) — the React + Primer app,
//      served by the loopback server at /main.js and /main.css. React, Primer,
//      the primitives theme CSS, and Motion (motion/react) are all
//      bundled in (local assets, no CDN). esbuild emits the sibling main.css
//      automatically because main.tsx imports CSS.
//
// Usage: `npm run build`   (one-shot, both bundles)
//        `npm run watch`   (rebuild both on change — live dev)

import * as esbuild from "esbuild";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// copilot-canvas-kit is a symlinked file: dep with its OWN node_modules/react.
// esbuild follows the symlink and would otherwise bundle a SECOND copy of React,
// leaving two independent dispatchers — the kit's hooks then read a null
// dispatcher and the app crashes on mount with
// "Cannot read properties of null (reading 'useSyncExternalStore')".
// Pin every react/react-dom import (app + kit) to this package's single copy.
const reactAlias = {
    react: path.resolve(__dirname, "node_modules/react"),
    "react-dom": path.resolve(__dirname, "node_modules/react-dom"),
};

/** @type {import("esbuild").BuildOptions} */
const nodeConfig = {
    entryPoints: ["src/extension.ts"],
    outfile: "extension.mjs",
    bundle: true,
    platform: "node",
    format: "esm",
    target: "node20",
    external: ["@github/copilot-sdk", "@github/copilot-sdk/*"],
    legalComments: "none",
    banner: {
        js:
            "// AUTO-GENERATED from src/ by build.mjs — do not edit this file directly.\n" +
            "// Edit the TypeScript sources in src/ and run `npm run build`.\n" +
            // Bundled CJS deps (Octokit's dependency tree) call require() for node
            // builtins. esbuild's ESM output otherwise wraps those in a shim that
            // throws "Dynamic require ... is not supported", so provide a real one.
            "import { createRequire as __cr } from 'node:module';\n" +
            "const require = __cr(import.meta.url);",
    },
    logLevel: "info",
};

/** @type {import("esbuild").BuildOptions} */
const webConfig = {
    entryPoints: ["web/main.tsx"],
    outfile: "web/main.js",
    bundle: true,
    platform: "browser",
    format: "esm",
    target: "es2020",
    jsx: "automatic",
    alias: reactAlias,
    loader: { ".css": "css" },
    define: { "process.env.NODE_ENV": '"production"' },
    minify: true,
    legalComments: "none",
    logLevel: "info",
};

if (process.argv.includes("--watch")) {
    const nodeCtx = await esbuild.context(nodeConfig);
    const webCtx = await esbuild.context(webConfig);
    await Promise.all([nodeCtx.watch(), webCtx.watch()]);
    process.stderr.write("watching src/ and web/ for changes…\n");
} else {
    await Promise.all([esbuild.build(nodeConfig), esbuild.build(webConfig)]);
}
