// esbuild driver: two bundles.
//
//   1. src/extension.ts → extension.mjs — the Node entry the CLI loads. The
//      Copilot SDK is marked external (CLI auto-resolves it; never bundle).
//      Octokit + yaml are bundled in so the extension is a single self-contained
//      ESM file with no runtime node_modules dependency.
//   2. web/anim.ts → web/anim.js — the browser-side Motion animation layer,
//      served by the loopback server at /anim.js and imported by index.html.
//      Motion is bundled in (local asset, no CDN).
//
// Usage: `npm run build`   (one-shot, both bundles)
//        `npm run watch`   (rebuild both on change)

import * as esbuild from "esbuild";

/** @type {import("esbuild").BuildOptions} */
const nodeConfig = {
    entryPoints: ["src/extension.ts"],
    outfile: "extension.mjs",
    bundle: true,
    platform: "node",
    format: "esm",
    target: "node20",
    external: ["@github/copilot-sdk", "@github/copilot-sdk/*"],
    legalComments: "none",
    banner: {
        js:
            "// AUTO-GENERATED from src/ by build.mjs — do not edit this file directly.\n" +
            "// Edit the TypeScript sources in src/ and run `npm run build`.\n" +
            // Bundled CJS deps (Octokit's dependency tree) call require() for node
            // builtins. esbuild's ESM output otherwise wraps those in a shim that
            // throws "Dynamic require ... is not supported", so provide a real one.
            "import { createRequire as __cr } from 'node:module';\n" +
            "const require = __cr(import.meta.url);",
    },
    logLevel: "info",
};

/** @type {import("esbuild").BuildOptions} */
const webConfig = {
    entryPoints: ["web/anim.ts"],
    outfile: "web/anim.js",
    bundle: true,
    platform: "browser",
    format: "esm",
    target: "es2020",
    minify: true,
    legalComments: "none",
    banner: { js: "// AUTO-GENERATED from web/anim.ts by build.mjs — do not edit directly." },
    logLevel: "info",
};

if (process.argv.includes("--watch")) {
    const nodeCtx = await esbuild.context(nodeConfig);
    const webCtx = await esbuild.context(webConfig);
    await Promise.all([nodeCtx.watch(), webCtx.watch()]);
    process.stderr.write("watching src/ and web/ for changes…\n");
} else {
    await Promise.all([esbuild.build(nodeConfig), esbuild.build(webConfig)]);
}
