// Shared esbuild configs, no side effects. `build.mjs` runs the two committed
// bundles (extension.mjs + web/main.js); `dev.mjs` reuses them for watch mode
// and adds devCanvasConfig — a Node bundle of the SDK-free canvas wiring that
// the dev server imports to serve the app as a plain webpage.

import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// copilot-canvas-kit is a symlinked file: dep with its OWN node_modules/react.
// esbuild follows the symlink and would otherwise bundle a SECOND copy of React,
// leaving two independent dispatchers — the kit's hooks then read a null
// dispatcher and the app crashes on mount with
// "Cannot read properties of null (reading 'useSyncExternalStore')".
// Pin every react/react-dom import (app + kit) to this package's single copy.
export const reactAlias = {
    react: path.resolve(__dirname, "node_modules/react"),
    "react-dom": path.resolve(__dirname, "node_modules/react-dom"),
};

// Bundled CJS deps (Octokit's dependency tree) call require() for node
// builtins. esbuild's ESM output otherwise wraps those in a shim that throws
// "Dynamic require ... is not supported", so provide a real one.
const REQUIRE_SHIM =
    "import { createRequire as __cr } from 'node:module';\n" +
    "const require = __cr(import.meta.url);";

const SDK_EXTERNAL = ["@github/copilot-sdk", "@github/copilot-sdk/*"];

/** @type {import("esbuild").BuildOptions} */
export const nodeConfig = {
    entryPoints: ["src/extension.ts"],
    outfile: "extension.mjs",
    bundle: true,
    platform: "node",
    format: "esm",
    target: "node20",
    external: SDK_EXTERNAL,
    legalComments: "none",
    banner: {
        js:
            "// AUTO-GENERATED from src/ by build.mjs — do not edit this file directly.\n" +
            "// Edit the TypeScript sources in src/ and run `npm run build`.\n" +
            REQUIRE_SHIM,
    },
    logLevel: "info",
};

/** @type {import("esbuild").BuildOptions} */
export const webConfig = {
    entryPoints: ["web/main.tsx"],
    outfile: "web/main.js",
    bundle: true,
    platform: "browser",
    format: "esm",
    target: "es2020",
    jsx: "automatic",
    alias: reactAlias,
    loader: { ".css": "css" },
    define: { "process.env.NODE_ENV": '"production"' },
    minify: true,
    legalComments: "none",
    logLevel: "info",
};

// Dev-only: the canvas wiring (src/canvas.ts) bundled on its own, with the SDK
// externalized (it's a type-only import there, so nothing SDK actually lands in
// the output). dev.mjs imports the result to open a canvas instance without the
// Copilot CLI. Emitted under .dev/ (gitignored).
/** @type {import("esbuild").BuildOptions} */
export const devCanvasConfig = {
    entryPoints: ["src/canvas.ts"],
    outfile: ".dev/canvas.mjs",
    bundle: true,
    platform: "node",
    format: "esm",
    target: "node20",
    external: SDK_EXTERNAL,
    legalComments: "none",
    banner: { js: REQUIRE_SHIM },
    logLevel: "info",
};
